---

 - hosts: all
   become: true

   tasks:
    - name: copy file with owner & permissions
      ansible.builtin.copy: 
        src: /home/beardwin/devopsjourney/dfcleanup-python-docker/docker-compose.yml       # push docker compose file to target host
        dest: /home/beardwin/docker-compose.yml


    - name: run docker-compose up
      community.docker.docker_compose:
        project_src: /home/beardwin/
        files:
          - "docker-compose.yml"
        state: present
        recreate: always
    
    - name: get docker container logs
      ansible.builtin.shell: docker logs df-clean-up
      register: docker_container_logs

    - debug:
        msg: "{{ docker_container_logs.stdout }}"